version: "3.7"
services:
    site:
        volumes: 
            - ./code:/var/www/html
        build: ./containers/web
        ports:
            - "80:80"
            - "443:443"
        tty: true
        hostname: projeto-site-adm
        container_name: projeto-site-adm
        networks:
            vpcbr:
                ipv4_address: 172.28.0.2
        depends_on:
            - db
    db:
        build: ./containers/db
        ports: 
            - "3306:3306"
        hostname: db-adm
        container_name: db-adm
        networks:
            vpcbr:
                ipv4_address: 172.28.0.3
networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16